language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "16"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
script: npm test
before_script:
  - psql -c 'create database minidb' -U postgres
services:
  - postgresql